import datetime
import os
import subprocess


def get_git_summary():
    try:
        status = subprocess.check_output(["git", "status", "--short"]).decode("utf-8")
        last_commit = subprocess.check_output(["git", "log", "-1", "--pretty=format:%s"]).decode(
            "utf-8"
        )
        return status, last_commit
    except Exception:
        return "Unknown", "None"


def generate_snapshot():
    status, last_commit = get_git_summary()
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    snapshot_path = "docs/research/context-snapshot.md"
    os.makedirs(os.path.dirname(snapshot_path), exist_ok=True)

    content_template = f"""# 🧠 Work Context Snapshot
Generated: {{timestamp}}

## 🚀 Last Known State
**Last Commit**: {last_commit}

## 📝 Pending Changes (Staged)
```text
{status if status.strip() else "No pending changes tracked by Git."}
```

## 🏗️ Active Components
- **API**: FastAPI with HTMX Dashboard
- **Manager**: Multi-process Bot Orchestrator
- **DB**: QuestDB + SQLite (Alembic)
- **Cache**: Redis

## 🎯 Current Focus
This snapshot was automatically generated by the `pre-commit` hook to ensure the project's 'Brain' remains in sync with the codebase.
"""
    new_content = content_template.format(timestamp=now)

    if os.path.exists(snapshot_path):
        with open(snapshot_path, "r") as f:
            old_content = f.read()

        # Check if content has changed (ignoring the timestamp line)
        old_lines = old_content.splitlines()
        new_lines = new_content.splitlines()

        if len(old_lines) == len(new_lines):
            # Line 1 is header, Line 2 is timestamp
            if old_lines[0] == new_lines[0] and old_lines[2:] == new_lines[2:]:
                print("✨ No functional context changes detected. Skipping update.")
                return

    with open(snapshot_path, "w") as f:
        f.write(new_content)
    print(f"✅ Context snapshot saved to {snapshot_path}")


if __name__ == "__main__":
    generate_snapshot()
